ALTER TABLE blood_requests
    MODIFY COLUMN blood_type ENUM('A+','A-','B+','B-','AB+','AB-','O+','O-') NOT NULL,
    MODIFY COLUMN urgency_level ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'MEDIUM',
    MODIFY COLUMN status ENUM('PENDING', 'APPROVED_PARTIALLY_FULFILLED', 'REJECTED', 'FULFILLED') DEFAULT 'PENDING',
    ADD COLUMN approved_at TIMESTAMP NULL;
